#!/bin/bash

usage () {
    echo "Usage: $0 --host <host> --admin <admin> --password <admin_pass> --dbname <db_name>"
    exit 1
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --host) DB_HOST="$2"; shift 2;;
        --admin) DB_ADMIN="$2"; shift 2;;
        --password) DB_PASS="$2"; shift 2;;
        --dbname) DB_NAME="$2"; shift 2;;
        --help) usage;;
        *) echo "Unknown option: $1"; exit 1;;
    esac
done

if [[ -z "$DB_HOST" || -z "$DB_ADMIN" || -z "$DB_PASS" || -z "$DB_NAME" ]]; then
    echo "Error: Missing parameters."
    usage
    exit 1
fi

echo "===> Creating database $DB_NAME on $DB_HOST..."
export MYSQL_PWD=$DB_PASS
RESULT=$(mysql -h "$DB_HOST" -u"$DB_ADMIN" --skip-column-names -e "SHOW DATABASES LIKE '$DB_NAME'")
echo $RESULT
if [ "$RESULT" == "$DB_NAME" ]; then
    echo "===> Database alresdy exists. Skipping creation."
else
    mysql -h "$DB_HOST" -u"$DB_ADMIN" -p"$DB_PASS" -e "
    CREATE DATABASE IF NOT EXISTS $DB_NAME;
    FLUSH PRIVILEGES;
    "
    echo "===> Database $DB_NAME created."
fi
