#!/bin/bash

while [[ $# -gt 0 ]]; do
    case "$1" in
        --host) DB_HOST="$2"; shift 2;;
        --admin) DB_ADMIN="$2"; shift 2;;
        --password) DB_PASS="$2"; shift 2;;
        --dbname) DB_NAME="$2"; shift 2;;
        --dbuser) DB_USER="$2"; shift 2;;
        --dbpass) DB_USER_PASS="$2"; shift 2;;
        --help) echo "Usage: $0 --host <host> --admin <admin> --password <admin_pass> --dbname <db_name> --dbuser <db_user> --dbpass <db_user_pass>"; exit 0;;
        *) echo "Unknown option: $1"; exit 1;;
    esac
done

mysql -h $DB_HOST -u$DB_ADMIN -p$DB_PASS --skip-ssl -e "
CREATE DATABASE IF NOT EXISTS $DB_NAME;
CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED WITH mysql_native_password BY '$DB_USER_PASS';
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'%';
FLUSH PRIVILEGES;
"